//
//  MainViewController.h
//  MySampleApp
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import <UIKit/UIKit.h>
#import <Parse/Parse.h>
#import <MessageUI/MessageUI.h>
#import "LocationManager.h"

@interface MainViewController : UIViewController <LocationManagerDelegate,MFMessageComposeViewControllerDelegate> {
   LocationManager* mLocationManager;
   BOOL showTeamList;
}
@property (weak, nonatomic) IBOutlet UIActivityIndicatorView *_activityIndicator;

@property (strong, nonatomic) PFObject* mCurrentTeam;
@end

@interface FeatureDescriptionViewController : UIViewController

@end
