//
// AWSConfiguration.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:d22a1706-43ad-4f29-9f22-674c23869fe0"
// PUSH
#define AWS_SNS_PLATFORM_APPLICATION_ARN @"arn:aws:sns:us-east-1:202699945646:app/APNS_SANDBOX/buddyproject_MOBILEHUB_8225340"
#define AWS_SNS_ALL_DEVICE_TOPIC_ARN @"arn:aws:sns:us-east-1:202699945646:buddyproject_alldevices_MOBILEHUB_8225340"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"buddyproject-userfiles-mobilehub-8225340"
